"""empty message

Revision ID: 79a670cd94e7
Revises: e4e51bfd23e1
Create Date: 2024-11-04 22:51:17.110176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a670cd94e7'
down_revision: Union[str, None] = 'e4e51bfd23e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_tag_product_uuid_fkey', 'product_tag', type_='foreignkey')
    op.drop_constraint('product_tag_tag_uuid_fkey', 'product_tag', type_='foreignkey')
    op.create_foreign_key(None, 'product_tag', 'tag', ['tag_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_tag', 'products', ['product_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_tag', type_='foreignkey')
    op.drop_constraint(None, 'product_tag', type_='foreignkey')
    op.create_foreign_key('product_tag_tag_uuid_fkey', 'product_tag', 'tag', ['tag_uuid'], ['uuid'])
    op.create_foreign_key('product_tag_product_uuid_fkey', 'product_tag', 'products', ['product_uuid'], ['uuid'])
    # ### end Alembic commands ###
