"""empty message

Revision ID: e0f674c78083
Revises: 43f9b11d3939
Create Date: 2024-10-15 12:12:09.171627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f674c78083'
down_revision: Union[str, None] = '43f9b11d3939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product_tag',
    sa.Column('tag_uuid', sa.Uuid(), nullable=True),
    sa.Column('product_uuid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_uuid'], ['products.uuid'], ),
    sa.ForeignKeyConstraint(['tag_uuid'], ['tag.uuid'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
