"""empty message

Revision ID: e4e51bfd23e1
Revises: e0f674c78083
Create Date: 2024-10-15 13:43:30.712859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e51bfd23e1'
down_revision: Union[str, None] = 'e0f674c78083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tag', sa.Column('uuid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_tag', 'uuid')
    # ### end Alembic commands ###
